### PR TITLE
:whale: update peddy to use new docker and bump workflow version number

### PR DESCRIPTION
**Pull request by sickler-alex**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

This updates the joint genotyping workflow to use the new peddy docker.

Fixes # partially https://app.zenhub.com/workspaces/d3b-bfx-5cdd720eed0dce4209e0b8a5/issues/d3b-center/bixu-tracker/91

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] [Cavatica test with peddy's example data](https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/39a10cd3-59b7-4af2-b4a5-3ae4821e5c12/)
- [X] [Cavatica test with full workflow](https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/f229781f-95b0-4a58-b893-f2137299f2e1/)

**Test Configuration**:
* Environment:
* Test files:

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by dmiller15 — APPROVED** [review]
👍

**Review by migbro — APPROVED** [review]
This looks good! Maybe for slight reassurance, if you could point me to, on the full run, the version that used the old peddy docker to compare results? Thanks!

**Comment by sickler-alex** [comment]
@migbro this is the run that I reran (after having to unarchive and reindex the vcf file). It looks like the outputs have been deleted though.
https://cavatica.sbgenomics.com/u/kfdrc-harmonization/kf-reference-pipeline/tasks/9ad92245-6bf5-4345-9aba-89b572fa924c/

**Comment by migbro** [comment]
Thanks @sickler-alex . I suppose that's good enough - the error log complained about an interval not being found at the exact same position, so seems like an indicator that it ran the same way.

**Pull request merged**
